#!/usr/bin/env python3
"""
Export a Gephi-ready edge CSV from all_matches.csv.

Input:
  - all_matches.csv generated by enumerate_fixed_query_all.py
  - fixed_query.json generated by citation_text_case_study.py
  - the same real graph data source used during matching

Output:
  - gephi_edges.csv: edge list for Gephi import
  - gephi_nodes.csv: optional node table with labels/roles/highlight attributes
  - gephi_export_summary.json: export statistics and selected representative matches

The edge CSV contains the union of:
  1) all vertices appearing in all enumerated matches;
  2) optionally, their k-hop surrounding neighbors in the real graph;
  3) all real graph edges induced by that selected vertex set.

It does not add any artificial edges. Match/query edges are only annotated.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
from collections import Counter, defaultdict, deque
from pathlib import Path
from typing import Dict, List, Set, Tuple, Optional

import numpy as np
import pandas as pd

import citation_text_case_study as base

MappingExt = Dict[str, str]
EdgeKey = Tuple[int, int]


def ensure_dir(path: str | Path) -> None:
    Path(path).mkdir(parents=True, exist_ok=True)


def clean_cell(x) -> str:
    if pd.isna(x):
        return ""
    return str(x)


def truncate(s: str, n: int = 120) -> str:
    s = re.sub(r"\s+", " ", str(s or "")).strip()
    if len(s) <= n:
        return s
    return s[: n - 3].rstrip() + "..."


def edge_key(a: int, b: int, undirected: bool = True) -> EdgeKey:
    if undirected and a > b:
        return (b, a)
    return (a, b)


def external_edge_key(graph: base.TextGraph, a: int, b: int, undirected: bool = True) -> Tuple[str, str]:
    ea, eb = graph.node_ids[a], graph.node_ids[b]
    if undirected and ea > eb:
        return (eb, ea)
    return (ea, eb)


def infer_qids_from_matches(df: pd.DataFrame) -> List[str]:
    qids = []
    for col in df.columns:
        if col.endswith("_node_id"):
            qids.append(col[: -len("_node_id")])
    def qkey(q: str):
        m = re.match(r"q(\d+)$", q)
        return (0, int(m.group(1))) if m else (1, q)
    return sorted(qids, key=qkey)


def read_matches(path: str | Path, qids: Optional[List[str]] = None) -> List[dict]:
    df = pd.read_csv(path)
    if qids is None:
        qids = infer_qids_from_matches(df)
    matches = []
    for _, row in df.iterrows():
        mapping: MappingExt = {}
        sims: Dict[str, float] = {}
        ok = True
        for qid in qids:
            col = f"{qid}_node_id"
            if col not in df.columns or pd.isna(row[col]):
                ok = False
                break
            mapping[qid] = str(row[col])
            scol = f"{qid}_similarity"
            if scol in df.columns and not pd.isna(row[scol]):
                sims[qid] = float(row[scol])
        if not ok:
            continue
        mid = int(row["match_id"]) if "match_id" in df.columns and not pd.isna(row["match_id"]) else len(matches) + 1
        mn = float(row["min_similarity"]) if "min_similarity" in df.columns and not pd.isna(row["min_similarity"]) else min(sims.values()) if sims else 0.0
        sm = float(row["sum_similarity"]) if "sum_similarity" in df.columns and not pd.isna(row["sum_similarity"]) else sum(sims.values())
        gt_raw = row.get("is_ground_truth", False)
        is_gt = str(gt_raw).lower() in {"true", "1", "yes"}
        matches.append({
            "match_id": mid,
            "mapping": mapping,
            "similarities": sims,
            "min_similarity": mn,
            "sum_similarity": sm,
            "is_ground_truth": is_gt,
        })
    return matches


def select_two_representatives(matches: List[dict], qids: List[str], prefer_gt: bool = True) -> Tuple[Optional[dict], Optional[dict]]:
    """Select two non-overlapping representative matches if possible.

    The first is the ground-truth match when present; otherwise the best match by
    min similarity then sum similarity. The second is the highest-quality match
    whose image set is disjoint from the first. If none exists, return None for B.
    """
    if not matches:
        return None, None
    ranked = sorted(matches, key=lambda m: (m["min_similarity"], m["sum_similarity"], -m["match_id"]), reverse=True)
    gt = [m for m in matches if m.get("is_ground_truth")]
    a = gt[0] if (prefer_gt and gt) else ranked[0]
    aset = set(a["mapping"].values())
    b_candidates = [m for m in ranked if m["match_id"] != a["match_id"] and set(m["mapping"].values()).isdisjoint(aset)]
    return a, (b_candidates[0] if b_candidates else None)


def load_graph(args: argparse.Namespace) -> base.TextGraph:
    if args.dataset == "ogbn-arxiv":
        return base.load_ogbn_arxiv(args)
    return base.load_csv_graph(args)


def k_hop_context(graph: base.TextGraph, seeds: Set[int], hops: int, max_neighbors_per_seed: int = 0) -> Set[int]:
    if hops <= 0:
        return set(seeds)
    selected = set(seeds)
    frontier = set(seeds)
    for _ in range(hops):
        nxt: Set[int] = set()
        for v in sorted(frontier):
            neigh = sorted(graph.adj[v])
            if max_neighbors_per_seed > 0:
                neigh = neigh[:max_neighbors_per_seed]
            for u in neigh:
                if u not in selected:
                    nxt.add(u)
        selected.update(nxt)
        frontier = nxt
        if not frontier:
            break
    return selected


def main() -> None:
    p = argparse.ArgumentParser(description="Export all-match neighborhood edges for Gephi")
    p.add_argument("--all-matches-csv", required=True, help="all_matches.csv from enumerate_fixed_query_all.py")
    p.add_argument("--load-query", required=True, help="fixed_query.json used by the all-match run")
    p.add_argument("--out", default="output_gephi", help="output directory")
    p.add_argument("--edge-out", default="gephi_edges.csv")
    p.add_argument("--node-out", default="gephi_nodes.csv")
    p.add_argument("--context-hop", type=int, default=1, help="include k-hop neighbors around all matched vertices; 0 means matched vertices only")
    p.add_argument("--max-neighbors-per-seed", type=int, default=0, help="optional cap per frontier node for context expansion; 0 means no cap")
    p.add_argument("--prefer-ground-truth", action="store_true", default=True)
    p.add_argument("--no-prefer-ground-truth", dest="prefer_ground_truth", action="store_false")

    # Same graph-loading options as the matching scripts.
    p.add_argument("--dataset", default="csv", choices=["csv", "ogbn-arxiv"])
    p.add_argument("--vertices-csv")
    p.add_argument("--edges-csv")
    p.add_argument("--id-col", default="id")
    p.add_argument("--src-col", default="src")
    p.add_argument("--dst-col", default="dst")
    p.add_argument("--text-cols", default=None)
    p.add_argument("--label-col", default="label")
    p.add_argument("--year-col", default="year")
    p.add_argument("--ogb-root", default="dataset")
    p.add_argument("--titleabs", default=None)
    p.add_argument("--nodeidx2paperid", default=None)
    p.add_argument("--label-filter", default=None)
    p.add_argument("--max-nodes", type=int, default=50000)
    p.add_argument("--seed", type=int, default=42, help="random seed used when --max-nodes subsamples ogbn-arxiv")
    p.add_argument("--min-text-words", type=int, default=20)
    p.add_argument("--match-undirected", action="store_true", default=True)
    p.add_argument("--directed-match", dest="match_undirected", action="store_false")
    args = p.parse_args()
    if args.max_nodes == 0:
        args.max_nodes = None

    outdir = Path(args.out)
    ensure_dir(outdir)

    print("Loading graph...")
    graph = load_graph(args)
    print(f"Loaded {graph.source_name}: {len(graph.node_ids)} vertices")

    q = base.load_query(args.load_query, graph)
    qids = q.qids
    qedges = {tuple(sorted(e)) for e in q.query_edges}
    matches = read_matches(args.all_matches_csv, qids=qids)
    if not matches:
        raise ValueError("No matches read from all_matches.csv")
    print(f"Loaded {len(matches)} matches")

    # Convert match mappings from external node ids to internal graph indices.
    converted = []
    for m in matches:
        internal = {}
        missing = []
        for qid, nid in m["mapping"].items():
            if nid not in graph.id_to_idx:
                missing.append(nid)
            else:
                internal[qid] = graph.id_to_idx[nid]
        if missing:
            raise ValueError(f"Match {m['match_id']} contains nodes not in graph: {missing[:5]}")
        mm = dict(m)
        mm["internal_mapping"] = internal
        converted.append(mm)
    matches = converted

    rep_a, rep_b = select_two_representatives(matches, qids, args.prefer_ground_truth)
    rep_ids = set()
    if rep_a:
        rep_ids.add(rep_a["match_id"])
    if rep_b:
        rep_ids.add(rep_b["match_id"])
    print("Representative match A:", rep_a["match_id"] if rep_a else None)
    print("Representative match B:", rep_b["match_id"] if rep_b else None)

    # Matched vertices and per-node attributes.
    matched_vertices: Set[int] = set()
    node_match_count: Counter[int] = Counter()
    node_roles: Dict[int, Counter[str]] = defaultdict(Counter)
    node_match_ids: Dict[int, List[int]] = defaultdict(list)
    node_highlight: Dict[int, Set[str]] = defaultdict(set)

    # Matched query-edges across all matches: count how often each real edge is used as a query edge.
    match_edge_count: Counter[EdgeKey] = Counter()
    match_edge_ids: Dict[EdgeKey, List[int]] = defaultdict(list)
    highlight_edge: Dict[EdgeKey, Set[str]] = defaultdict(set)

    for m in matches:
        mid = m["match_id"]
        im = m["internal_mapping"]
        for qid, v in im.items():
            matched_vertices.add(v)
            node_match_count[v] += 1
            node_roles[v][qid] += 1
            if len(node_match_ids[v]) < 50:
                node_match_ids[v].append(mid)
        for a, b in qedges:
            va, vb = im[a], im[b]
            ek = edge_key(va, vb, undirected=args.match_undirected)
            match_edge_count[ek] += 1
            if len(match_edge_ids[ek]) < 50:
                match_edge_ids[ek].append(mid)

    if rep_a:
        for v in rep_a["internal_mapping"].values():
            node_highlight[v].add("A")
        for a, b in qedges:
            ek = edge_key(rep_a["internal_mapping"][a], rep_a["internal_mapping"][b], undirected=args.match_undirected)
            highlight_edge[ek].add("A")
    if rep_b:
        for v in rep_b["internal_mapping"].values():
            node_highlight[v].add("B")
        for a, b in qedges:
            ek = edge_key(rep_b["internal_mapping"][a], rep_b["internal_mapping"][b], undirected=args.match_undirected)
            highlight_edge[ek].add("B")

    selected_vertices = k_hop_context(
        graph,
        matched_vertices,
        hops=args.context_hop,
        max_neighbors_per_seed=args.max_neighbors_per_seed,
    )
    print(f"Matched vertices: {len(matched_vertices)}; selected with context: {len(selected_vertices)}")

    # Build Gephi edge rows from real graph edges induced by selected_vertices.
    edge_rows = []
    seen_edges: Set[EdgeKey] = set()
    for u in sorted(selected_vertices):
        for v in sorted(graph.adj[u]):
            if v not in selected_vertices:
                continue
            ek = edge_key(u, v, undirected=args.match_undirected)
            if args.match_undirected and ek in seen_edges:
                continue
            seen_edges.add(ek)
            mu = u in matched_vertices
            mv = v in matched_vertices
            mcnt = int(match_edge_count.get(ek, 0))
            h = ";".join(sorted(highlight_edge.get(ek, set())))
            if h:
                kind = "highlight_match_edge"
            elif mcnt > 0:
                kind = "matched_query_edge"
            elif mu or mv:
                kind = "context_incident_edge"
            else:
                kind = "context_edge"
            # Weight can be used in Gephi for thickness. Query edges used in many matches get larger weight.
            weight = 1.0 + float(mcnt)
            edge_rows.append({
                "Source": graph.node_ids[ek[0]],
                "Target": graph.node_ids[ek[1]],
                "Type": "Undirected" if args.match_undirected else "Directed",
                "Weight": weight,
                "edge_kind": kind,
                "matched_endpoint_count": int(mu) + int(mv),
                "match_edge_count": mcnt,
                "highlight": h,
                "support_match_ids": ";".join(map(str, match_edge_ids.get(ek, []))),
            })

    edge_path = outdir / args.edge_out
    with edge_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "Source", "Target", "Type", "Weight", "edge_kind", "matched_endpoint_count",
            "match_edge_count", "highlight", "support_match_ids"
        ])
        writer.writeheader()
        writer.writerows(edge_rows)

    # Optional but strongly useful in Gephi: node table for labels/colors/sizes.
    node_rows = []
    for v in sorted(selected_vertices):
        roles = ";".join(f"{qid}:{cnt}" for qid, cnt in node_roles.get(v, Counter()).most_common())
        highlight = ";".join(sorted(node_highlight.get(v, set())))
        if highlight:
            kind = "highlight_match_vertex"
        elif v in matched_vertices:
            kind = "matched_vertex"
        else:
            kind = "context_vertex"
        meta = []
        if graph.labels is not None:
            meta.append(f"label={graph.labels[v]}")
        if graph.years is not None:
            meta.append(f"year={graph.years[v]}")
        node_rows.append({
            "Id": graph.node_ids[v],
            "Label": truncate(graph.titles[v], 80) if graph.titles else graph.node_ids[v],
            "node_kind": kind,
            "is_matched_vertex": int(v in matched_vertices),
            "match_count": int(node_match_count.get(v, 0)),
            "query_roles": roles,
            "highlight": highlight,
            "metadata": "; ".join(meta),
            "title": graph.titles[v] if graph.titles else "",
            "text": truncate(graph.texts[v], 500) if graph.texts else "",
            "support_match_ids": ";".join(map(str, node_match_ids.get(v, []))),
        })

    node_path = outdir / args.node_out
    with node_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "Id", "Label", "node_kind", "is_matched_vertex", "match_count", "query_roles",
            "highlight", "metadata", "title", "text", "support_match_ids"
        ])
        writer.writeheader()
        writer.writerows(node_rows)

    summary = {
        "all_matches_csv": str(args.all_matches_csv),
        "query_file": str(args.load_query),
        "num_matches": len(matches),
        "num_query_vertices": len(qids),
        "num_query_edges": len(qedges),
        "matched_vertices": len(matched_vertices),
        "selected_vertices_with_context": len(selected_vertices),
        "exported_edges": len(edge_rows),
        "edge_csv": str(edge_path),
        "node_csv": str(node_path),
        "representative_A_match_id": rep_a["match_id"] if rep_a else None,
        "representative_B_match_id": rep_b["match_id"] if rep_b else None,
        "representative_A_min_similarity": rep_a["min_similarity"] if rep_a else None,
        "representative_B_min_similarity": rep_b["min_similarity"] if rep_b else None,
    }
    (outdir / "gephi_export_summary.json").write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")

    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
